services:
  frontend:
    build:
      context: ./paftys
    env_file:
      - ./paftys/.env.local
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./paftys:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
  backend_node_modules:
